### PR TITLE
Add workspace indexing

### PR DESCRIPTION
**Pull request by RoshanNagaram-eng**
- Added support for Indexing in Xcode on workspace projects
- Fixed some Enterprise Features

### CODE REVIEW

**Comment by intitni** [comment]
Do you mind moving this pull request to [CopilotForXcode](https://github.com/intitni/copilotforxcode)

**Comment by RoshanNagaram-eng** [comment]
Sure I can do that!

Any particular reason as to why though?


Roshan Nagaram

**Comment by intitni** [comment]
Thank you. This project is meant to be a subset of Copilot for Xcode and will only merge the updates when the Copilot for Xcode releases are stable enough. 

For example, your last pull request was actually merged into Copilot for Xcode and not yet available in this repo. If you could move this pull request, it would make this process easier.

**Comment by intitni** [comment]
included in #8

**Pull request closed without merging**
