### PR TITLE
Add support for Codeium Enterprise

### PR DESCRIPTION
**Pull request by fortenforge**
I haven't been able to test this since I don't know how to hook up the app to XCode, but it's simple enough that I think it should work.

### CODE REVIEW

**Comment by intitni** [comment]
You can test with this version 
https://github.com/intitni/CodeiumForXcode/releases/download/codeium%2F0.19.2/test.app.zip

**Comment by fortenforge** [comment]
Thanks! Unfortunately, it didn't work, but I think I fixed it. Could you build me another test release?

**Comment by intitni** [comment]
Uploaded https://github.com/intitni/CodeiumForXcode/releases/download/codeium%2F0.19.2/test.2.app.zip

**Comment by fortenforge** [comment]
Cool, this works!

**Comment by intitni** [comment]
( • ̀ω•́ )b I will release it later

**Pull request merged**
